### ISSUE TITLE
Add anime to the top bar

### ISSUE THREAD

**Issue by et-irl** [AY2324S1-CS2103T-T12-1/tp#158]
The top bar is very lonely. We should add anime characters because it's funny in the top bar. Frfr if you agree leave a comment

**Comment by weiseng18** [comment]
+1 🚀

**Comment by proto-aiken-13** [comment]
I agree. We should add more NPC's and my cs3241 lab 3 render to the top bar!

**Comment by et-irl** [comment]
Skull Emoji
