### ISSUE TITLE
Error Message : Message Command Error Expected

### ISSUE THREAD

**Issue by Vanessamae23** [AY2324S1-CS2103T-T12-1/tp#166]
![image](https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/9929e687-be47-40bc-af70-054a0a260a98)

I missed the value for `pp/`, but i think the better error message would be about invalid formatting?

Current behavior :. PP number is out of range..

**Expected Behaviour :** Invalid command ..

**Comment by et-irl** [comment]
`inputPP 1 t/1 pp/2147483647` 
`inputPP 1 t/2 pp/2147483647` 

Current Final Participation Points: 2147483647*2
Expected Final Participation Points: -2
