### ISSUE TITLE
Can't seem to deassign assignment

### ISSUE THREAD

**Issue by Vanessamae23** [AY2324S1-CS2103T-T12-1/tp#168]
![image](https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/833ef75c-1fdc-4ceb-89eb-efa71e3f8857)

Is the behaviour to deassign require them to involve everybody?

**Comment by et-irl** [comment]
We have added the `deassignIndiv` command to deassign assignments individually. This should resolve your problem.
