### ISSUE TITLE
Command Error : Unmark Attendance for certain groups

### ISSUE THREAD

**Issue by Vanessamae23** [AY2324S1-CS2103T-T12-1/tp#169]
**Current behavior** :  Unmark attendance for certain groups say I assign a single member to mark one of the attendance then i unmark using the group function, is it I wont be able to unmark if the attendance was not made through assignGroup

**Expected behavior** :  i should be able to unmark regardless of whether the attendance was group based or individual

https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/b17a8ede-8c22-42e0-8268-766b0e9be3a8

**Comment by et-irl** [comment]
Please provide the steps of how to replicate this bug.
