### ISSUE TITLE
Bug: Updating a group to another group

### ISSUE THREAD

**Issue by Vanessamae23** [AY2324S1-CS2103T-T12-1/tp#171]
Am I allowed to update a group to another existing group since this is the behaviour if i do so but there is no error handling to the user

https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/9c3c6bdd-5271-4ee7-844a-3957e27e7658

![image](https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/f7aaf179-85b1-47c0-a5a2-0bdf6687b34e)

**Comment by et-irl** [comment]
Please provide the exact steps to replicate this error, as I am unable to do so.

**Comment by Vanessamae23** [comment]
> Please provide the exact steps to replicate this error, as I am unable to do so.


https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/64483302-e092-4b3e-8417-fedd09b255cd
