### ISSUE TITLE
Update the User Guide to be more user-friendly.

### ISSUE THREAD

**Issue by proto-aiken-13** [AY2324S1-CS2103T-T12-1/tp#180]
The user guide is well-formatted, but it suffers from some issues that affects its readability. These issues include the use of programming jargon that would otherwise come across confusing to the user as well as having large chunks of text.

https://docs.google.com/document/d/1Ti28hgEnp8yqWjVKx7q3wBTdUJcC5nLbS8QHF_0MOr4/edit?usp=sharing For more clarification on what I feel can be approved in the User Guide.

Related to #95

- [X] I have added the relevant tags related to this feature request.

**Describe the solution you'd like**
Follow these guidelines when updating the user guide:
- Must be clear and concise, and appeals to the lowest denominator of TA's
- If possible, try to show how features can compliment existing requirements of TA's in NUS in general.
- Update the installation guide to be easy to read and install.
- Do not use jargon as much as possible. If anything, the only three computing-related jargon you need to use are "commands",
"bugs" and "command line".

**Additional context**
For 2101, in accordance to Ms. Amy's feedback. To be done before the submission of the UG.

**Comment by lsyurea** [comment]
closes #296
