### ISSUE TITLE
[PE-D][Tester E] Ui formatting issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-1/tp#192]
When the window is being minimised horizontally, there is no horizontal scroll wheel for users to view the information that exceeds the window space. For example, the tutorial group of the students.

![image.png](https://raw.githubusercontent.com/yyyaohhh/ped/main/files/f87ee77f-d5e0-4729-8065-05fe386136c1.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yyyaohhh/ped#1

**Comment by et-irl** [comment]
From CS2103T:
> Also, accommodating 'extreme' inputs (e.g., a person name with 1000 characters) can be considered a nice-to-have feature, to be added in a future version (i.e., lack of it is not a bug).

This is nice-to-have, and will not be fixed this iteration.
