### ISSUE TITLE
[PE-D][Tester A] User Guide: Common Parameters section does not seem complete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-1/tp#198]
In the user guide, the Common Parameters section has 1 entry of the n/name tag, and 5 duplicate entries of the a/telegram handle tag. 

This can be problematic because it may be confusing to read 5 duplicates of the same entry, and seems like a mistake because there are other tags such as phone and email which may be deemed as a "common" parameter too.

A possible remedy is to add in more parameters and remove the 4 duplicate entries of a/telegram handle.

This image shows how the a/telegram tag entries are duplicate.
![image.png](https://raw.githubusercontent.com/Dioclei/ped/main/files/6a74ca49-b208-4235-9001-30592f47d603.png)

Common Parameters section may be quite important to some users so I put the severity as medium.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Dioclei/ped#1

**Comment by et-irl** [comment]
Your subjective opinion of importance is not relevant to the severity - there is an objective measure for it. This is `Severity.Low` - it is a minor inconvenience.
