### ISSUE TITLE
[PE-D][Tester E] Wrong exception thrown

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-1/tp#207]
Should be an error on wrong command format, instead of "Tutorial number is out of range" (and the number is 12, which is actually in range), because I used unmarkGroupAtd and added s/VR behind.

![image.png](https://raw.githubusercontent.com/yyyaohhh/ped/main/files/893bf14a-a259-4e2d-b159-3a2ae1d92dfe.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yyyaohhh/ped#3

**Comment by proto-aiken-13** [comment]
No status is needed for any of the attendance unmarking commands. Will look into this however.
