### ISSUE TITLE
[PE-D][Tester C] UI does not show all details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-1/tp#209]
![image.png](https://raw.githubusercontent.com/tayian/ped/main/files/82bb608f-6040-4e5a-8da0-f6d2c58eb0ac.png)

I tried the command `assignGroup tut33 n/thisisatestnewassignment whose name is very very very very very very very very very very very very very very very very very long m/50`

I am now not able to see the name of the entire assignment, as well as the total participation points.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tayian/ped#6

**Comment by et-irl** [comment]
From 2103T guidelines:

> Also, accommodating 'extreme' inputs (e.g., a person name with 1000 characters) can be considered a nice-to-have feature, to be added in a future version (i.e., lack of it is not a bug).

We will not fix it in this version.
