### ISSUE TITLE
[PE-D][Tester D] Group command seems to transfer a student from one group to another, unlike what is mentioned in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-1/tp#215]
in UG, what is said that group command Group students by classes.
However when i typed the following: `group 20 33' my students in group 20 had their groups changed to group 33. 

This really confuses the user. 

UG:
![Screenshot 2023-11-03 at 4.56.08 PM.png](https://raw.githubusercontent.com/vijay-shankaranand/ped/main/files/cac190bf-c3da-4abc-b81b-5d864703f457.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: vijay-shankaranand/ped#8

**Comment by Vanessamae23** [comment]
Solved but issue was not referred

![image](https://github.com/AY2324S1-CS2103T-T12-1/tp/assets/60029664/15823339-b507-400b-b451-13405b352bdc)

**Comment by et-irl** [comment]
ok if it was solved just close it lol
