### ISSUE TITLE
[PE-D][Tester A] Possible flaw with creating assignments of the same name with different max score

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-1/tp#216]
Two students can have assignments of the same name, but different max score, simply by using the `assignIndiv` command.

This is potentially problematic because gradeGroup attempts to grade all assignments with the same name, but is unable to grade if the score given is higher. Perhaps it would make more sense to make assignment names unique so this cannot happen.

![image.png](https://raw.githubusercontent.com/Dioclei/ped/main/files/22549dee-50e5-4942-bf49-4b7746d94265.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Dioclei/ped#2

**Comment by Vanessamae23** [comment]
I think we can just state in the UG that it is the intended behavior that all the assignment under the same group when done using `gradeGroup` must be below the maxScore
