### ISSUE TITLE
[PE-D][Tester D] Tutorial score accepts negative 0

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-1/tp#221]
Tutorial score accepts -0. Test input: `grade 1 n/tutorial2 g/80`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vijay-shankaranand/ped#10

**Comment by Choonyan02** [comment]
As we are not doing any operations here, -0 is effectively the same as 0.

**Comment by Vanessamae23** [comment]
this was already explained in the UG
