### ISSUE TITLE
Wrong installation method in the User Guide

### ISSUE THREAD

**Issue by et-irl** [AY2324S1-CS2103T-T12-1/tp#247]
**Describe the bug**
There are many ways to run the JAR file.
Furthermore, the current way specified by the User Guide does not work for users on Windows.
We want to only specify the command line `java -jar` method.

- [x] I have added the severity tag of this bug.

**Comment by Vanessamae23** [comment]
Guides done
- [ ] Linux
- [ ] Windows
- [ ] MacOS
