### ISSUE TITLE
Refine UI to suit the needs of the new project

### ISSUE THREAD

**Issue by et-irl** [AY2324S1-CS2103T-T12-1/tp#50]
The current UI is optimised for the address book project.

To modify it to suit our uses and features more, we need to change the UI.

**Comment by proto-aiken-13** [comment]
The current UI is optimised for the address book project.

To modify it to suit our uses and features more, we need to change the UI.

We need to re-factor UI components to be reflective of the modified classes
within the UI. In addition, we must also make list down the features we want
to add so as to reflect them on the UI.

Please respond to the issue with **what you wish to add on to the tP** with
what you wish to add. In addition, please take note of the dependencies the
UI classes need:

```
PersonCard class:
Uses the Label classes for:
name
id
phone
address
email
tags
```

**Comment by Choonyan02** [comment]
Should we replace address with telegram here? Also we can add in Attendance too. Attendance will be in the form of x/12 for now, where x refers to the number of tutorials attended
